### ISSUE TITLE
ACTIVIDAD 4

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-4-mapa-mental-SandyMarissaGs#1]
Sandy Marissa García Santiago.
ACTIVIDAD 4
Grupo:1BS.
![COMUNICACION ORAL Y ESCRITA FUNDAMENTOS DE INVESTIGACION](https://user-images.githubusercontent.com/112224739/191394464-6988a762-56cc-4df9-b002-01df7b1a3f6a.png)

**Comment by YaelTrinidad** [comment]
ACT 4 MAPA MENTAL
"TIPOS DE COMUNICACIÒN"
DEL 20% DE LA ACTIVIDAD, DADA LA RUBRICA OBTUVISTE EL 17.3%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
